blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^post$', views.boardpost, name='boardpost'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name = 'postSlug'),
    url(r'^(?P<post_id>[0-9]+)$', views.postView, name='postView'),
]

seoulmateapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^collections/', include('collection.urls', namespace="collection")),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^daehakgyo/', include('daehakgyo.urls', namespace="daehakgyo")),
    url(r'^lifeinkorea/', include('koreanlife.urls', namespace="koreanlife")),
	url(r'^end-user-license-agreement/',TemplateView.as_view(template_name='landingsite/end-user-license-agreement.html'),name='end-user-license-agreement'),
    url(r'^privacy-policy/',TemplateView.as_view(template_name='landingsite/privacy-policy.html'),name='privacy-policy'),
    url(r'^contact/thanks/',TemplateView.as_view(template_name='landingsite/thanks.html'),name='thanks'),
    url(r'^contact-us/',TemplateView.as_view(template_name='landingsite/contact_us.html'),name='contact-us'),
    url(r'^help-center/',TemplateView.as_view(template_name='landingsite/help-center.html'),name='help-center'),
    url(r'^$', include('landingsite.urls', namespace="landingsite")),
]

#urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


class Post(models.Model):
	post_author = models.CharField(max_length=250)
	post_author_photo = models.ImageField(upload_to='posts/author',blank=True)
	post_title = models.CharField(max_length=400)
	# post_name = models.CharField(max_length=400)
	post_photo = models.ImageField(upload_to='posts',blank=True)
	post_content = models.TextField()
	post_slug = models.SlugField(max_length=500,unique=True)
	post_modified =  models.DateTimeField('date modified',default=timezone.now)
	post_published =  models.DateTimeField('date published',default=timezone.now)
	post_type = models.CharField(max_length=200)
	is_live = models.BooleanField(default=False)

	def __str__(self):
		return self.post_title

	def save(self):
		if not self.id:
			self.post_published = timezone.now()
			self.post_slug = slugify(self.post_title)
		self.post_modified = datetime.datetime.now()
		return super(Post,self).save()


class Category(models.Model):
	post = models.ForeignKey(Post)
	cat_title = models.CharField(max_length=250, default="social")
	cat_pos = models.IntegerField(default=7)
	cat_description  = models.CharField(max_length=400)

	class Meta:
		verbose_name_plural = "categories"

	def __str__(self):
		return self.cat_title

# Declare the ForeignKey with related_query_name
class Tag(models.Model):
    post = models.ForeignKey(Post, related_name="tags")
    name = models.CharField(max_length=255)

blog/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,Http404
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt

from .models import Post


def index(request):
	posts = Post.objects.order_by('-post_published')
	context = {'posts': posts}	 
	# return HttpResponse(template.render(context))
	return render(request,'blog/blog_home.html', context)

def postView(request,post_id):
	post = get_object_or_404(Post,pk=post_id)
	return render(request,'blog/singlepost.html', {'post':post})

def postSlug(request,slug):
	post = get_object_or_404(Post,post_slug=slug)
	return render(request,'blog/singlepost.html', {'post':post})

@csrf_exempt
def boardpost(request):
    if request.method == "POST":
    	# print ("post method")
    	# print ('Raw Data: "%s"' % request.body)
        title = request.POST.get('title','NOTHING')
        # print (title)
        return HttpResponse("SUCCESS")
        # return  render(request, 'blog/blog_home.html',context_instance=RequestContext(request))
    else:
    	return  render(request, 'blog/blog_home.html',context_instance=RequestContext(request))

blog/templates/blog/blog_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - Blog</title>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - Blog" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/seoulmateapp" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." /> 
    <meta property="og:image"content="{% static 'landingsite/images/bridge-824609_1280.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/blog/" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>
</head>
<body>
  <nav class="pink accent-3" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Blog</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br><br><br><br><br>
      <h1 class="header center white-text">"Share your experiences with community"</h1>
      <div class="row center">
        <h5 class="header col s12 light"><span class="white-text"></span></h5>
      </div>
      <div class="row center">
        <a href="#" id="download-button" class="btn-large waves-effect waves-light light-blue">Read below</a>
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/bike-688699_1280.jpg' %}"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
      {% if posts %}
      {% for post in posts %}
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image" style="height:200px;" >
              <img src="{{ post.post_photo.url }}">
            </div>
            <div class="card-content">
            <span class="card-title activator grey-text text-darken-4 truncate" style="font-size: 21px;">{{ post.post_title}}</span>
            <p><a href="/blog/{{ post.post_slug }}">Read more</a></p>
            </div>
            <div class="card-action">
              <a style="color: #ff4081;" href="#"><span class="text-blue text-accent-2"> {% for cat in post.category_set.all %}
                  {{ cat.cat_title }}
              {% endfor %}</span></a>
              <a style="color: #ff80ab;" href='#'>{{ post.post_tags }}</a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h3>No posts are available.</h3>
        {% endif %}
      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer pink accent-3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="#!">Community</a></li>
            <li><a class="white-text" href="#!">Board</a></li>
            <li><a class="white-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>

blog/templates/blog/singlepost.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>{{ post.post_title}}</title>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta property="og:title" content="{{ post.post_title }}" />
  <meta property="og:description" content="{{ post.post_content }}" />
   <meta property="fb:app_id" content="222622874583781" />
  <meta property="og:url" content="http://seoulmateapp.co/blog/{{ post.id }}" />
  <meta property="og:image" content="http://seoulmateapp.co{{ post.post_photo.url }}" />
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

  </script>
</head>
<body>
<div id="fb-root"></div>
{% block js %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '222622874583781',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
{% endblock js %}
  <nav class="cyan darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/blog" class="brand-logo"><i class="material-icons">view_module</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/"><i class="material-icons">home</i></a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <!-- <div class="parallax-container" id="index-banner"> -->
      <div class="section cyan">
        <div class="row center">
          <div class="col s12 m8 l8 offset-m2 offset-l2">
          <h3>{{ post.post_title }}</h3>
          <br>
          <img class="circle" src="{{ post.post_author_photo.url }}" width="100">
          <h5>{{ post.post_author }}</h5>
          <p class="lime-text accent-4">{{ post.post_published|date}}</p>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="section">
          <div class="row">
          <div class="col s12 m12 l12">
          <h6 style="line-height: 140%;">{{ post.post_content|safe}}</h6>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
        {% if post.category_set.all %}
          <a class="waves-effect waves-light btn pink accent-2"><i 
          class="material-icons left"></i>{% for cat in post.category_set.all %}
                  {{ cat.cat_title }}
              {% endfor %}</a>
         {% endif %}
         &nbsp;&nbsp;&nbsp;
        {% if post.tag_set.all %}
        {% for tag in post.tag_set.all %}
          <a class="waves-effect waves-light btn pink accent-3"><i 
          class="material-icons left"></i> {{ tag.name }}</a>
         {% endfor %}
         {% endif %}
        </div>
      </div>
      <div class="divider"></div>
       {% if post.post_photo %}
      <div class="section">
        <div class="row">
          <div class="col s12">
            <img src="{{ post.post_photo.url }}" class="responsive-img">
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  <!-- </div> -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large lime accent-4">
      <i class="large material-icons">share</i>
    </a>
    <ul>
      <li><a class="btn-floating blue darken-1" 
      href="https://www.linkedin.com/shareArticle?mini=true&url=http://seoulmateapp.co/blog/{{post.id}}&title={{ post.post_title|urlencode }}&summary={{ post.post_content|urlencode }}&source=Seoul%20Mate"
      ><i class="fa  fa-linkedin  fa-2x" style="color:#fff;"></i></a></li>
      <li><a class="btn-floating light-blue darken-4" href="" onclick="fbshare()"><i class="fa  fa-facebook  fa-2x"></i></a></li>
      <li><a class="btn-floating light-blue accent-3" href="https://twitter.com/intent/tweet?text={{post.post_title|urlencode}}&url={{ 'http://seoulmateapp.co/blog/'|urlencode:''}}{{ post.id|urlencode:''}}&via=seoulmateme"><i class="fa  fa-twitter  fa-2x"></i></a></li>
      <li><a class="btn-floating red darken-2" href="https://plus.google.com/share?url={{ 'http://seoulmateapp.co/blog/'|urlencode:''}}{{ post.id|urlencode:''}}"><i class="fa fa-google-plus fa-2x"></i></a></li>
    </ul>
  </div>

  <footer class="page-footer cyan">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/latest">Blog</a></li>
            <li><a class="white-text" href="#!">MOOC Circle</a></li>
            <li><a class="white-text" href="#!">Seoul Mate</a></li>
            <li><a class="white-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" 
      href="http://materializecss.com">Materialize</a> and
       <a class="teal-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>

<script>
    function fbshare(){
        FB.ui({
          method: 'share',
          href: 'http://seoulmateapp.co/blog/{{ post.id }}',
          picture: 'http://seoulmateapp.co{{ post.post_photo.url }}',
          caption: '{{ post.post_title }}',
        }, function(response){});
    }
</script>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>