blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^post$', views.boardpost, name='boardpost'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name = 'postSlug'),
    url(r'^(?P<post_id>[0-9]+)$', views.postView, name='postView'),
]

landingsite/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^about/end-user-license-agreement$', views.eula, name='eula'),
    url(r'^$', views.index, name='index'),

]

seoulmateapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^collections/', include('collection.urls', namespace="collection")),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^daehakgyo/', include('daehakgyo.urls', namespace="daehakgyo")),
    url(r'^lifeinkorea/', include('koreanlife.urls', namespace="koreanlife")),
	url(r'^end-user-license-agreement/',TemplateView.as_view(template_name='landingsite/end-user-license-agreement.html'),name='end-user-license-agreement'),
    url(r'^privacy-policy/',TemplateView.as_view(template_name='landingsite/privacy-policy.html'),name='privacy-policy'),
    url(r'^contact/thanks/',TemplateView.as_view(template_name='landingsite/thanks.html'),name='thanks'),
    url(r'^contact-us/',TemplateView.as_view(template_name='landingsite/contact_us.html'),name='contact-us'),
    url(r'^help-center/',TemplateView.as_view(template_name='landingsite/help-center.html'),name='help-center'),
    url(r'^$', include('landingsite.urls', namespace="landingsite")),
]

#urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


class Post(models.Model):
	post_author = models.CharField(max_length=250)
	post_author_photo = models.ImageField(upload_to='posts/author',blank=True)
	post_title = models.CharField(max_length=400)
	# post_name = models.CharField(max_length=400)
	post_photo = models.ImageField(upload_to='posts',blank=True)
	post_content = models.TextField()
	post_slug = models.SlugField(max_length=500,unique=True)
	post_modified =  models.DateTimeField('date modified',default=timezone.now)
	post_published =  models.DateTimeField('date published',default=timezone.now)
	post_type = models.CharField(max_length=200)
	is_live = models.BooleanField(default=False)

	def __str__(self):
		return self.post_title

	def save(self):
		if not self.id:
			self.post_published = timezone.now()
			self.post_slug = slugify(self.post_title)
		self.post_modified = datetime.datetime.now()
		return super(Post,self).save()


class Category(models.Model):
	post = models.ForeignKey(Post)
	cat_title = models.CharField(max_length=250, default="social")
	cat_pos = models.IntegerField(default=7)
	cat_description  = models.CharField(max_length=400)

	class Meta:
		verbose_name_plural = "categories"

	def __str__(self):
		return self.cat_title

# Declare the ForeignKey with related_query_name
class Tag(models.Model):
    post = models.ForeignKey(Post, related_name="tags")
    name = models.CharField(max_length=255)

landingsite/models.py
from django.db import models

# Create your models here.

landingsite/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.mail import send_mail, BadHeaderError
from blog.models import Post
from collection.models import Collection

categories = {0: 'Korean Language', 1: 'News', 2: 'Media', 3: 'Jobs & Internships', 4:'Scholarships', 5:'Tourism', 6:'History & Culture', 7:'Social Media'}

def index(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        message = request.POST.get('message', '')
        from_email = request.POST.get('email', '')
        subject = 'Contact us - Seoul Mate website'
        if subject and message and from_email and first_name and last_name:
            try:
                message = message + "\n From : " + from_email
                send_mail(subject, message, from_email, ['seoulmate.me@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('/contact/thanks/')
    else :
        collections = Collection.objects.order_by('-createdAt')[:3]
        posts = Post.objects.order_by('-post_published')[:3]
        context = {'posts': posts,'collections':collections,'categories': categories}
        return render(request,'landingsite/index.html', context)

def eula(request):

    context = ""
    return render(request, 'landingsite/end-user-license-agreement.html', context)

landingsite/templates/landingsite/contact_us.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - Contact us</title>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - Contact us" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." /> 
    <meta property="og:image"content="{% static 'landingsite/images/bridge-824609_1280.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/contact/us" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Contact us</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center white-text" style="margin-top: 150px;">Write us a message</h1>
      <div class="row center">
        <h5 class="header col s12 text-dark-orange light"><span class="text-dark-orange"></span></h5>
      </div>
      <div class="row center">
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/fireworks-656248_1280.jpg' %}"></div>
  </div>
<br><br>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
<div class="row">
    <form action="{% url 'landingsite:index' %}" method="post" class="col s12">
{% csrf_token %}     
 <div class="row">
        <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
          <input name="first_name" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
          <input name="last_name" id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
          <input name="email" id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
          <textarea name="message" id="icon_prefix2" class="materialize-textarea" length="400"></textarea>
          <label for="icon_prefix2">Message</label>
        </div>
      </div>
      <div class="row">
      <div class="col s6 offset-s6 offset-m6"></div>
        <button class="btn-large waves-effect waves-light deep-orange" id="submit">Send</button>
        </div>
      </div>
    </form>
  </div>

      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="#!">Community</a></li>
            <li><a class="white-text" href="#!">Board</a></li>
            <li><a class="white-text" href="#!">Contact us</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>

landingsite/templates/landingsite/help-center.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - Help Center</title>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - Contact us" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/hassanabidpk89" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." /> 
    <meta property="og:image"content="{% static 'landingsite/images/bridge-824609_1280.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/help-center" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Help Center</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center white-text" style="margin-top: 150px;">Write us a message</h1>
      <div class="row center">
        <h5 class="header col s12 text-dark-orange light"><span class="text-dark-orange"></span></h5>
      </div>
      <div class="row center">
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/fireworks-656248_1280.jpg' %}"></div>
  </div>
<br><br>

  <div class="container">
    <div class="section">

     <!--   Icon Section   -->
<div class="row">
    <form action="{% url 'landingsite:index' %}" method="post" class="col s12">
{% csrf_token %}     
 <div class="row">
        <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
          <input name="first_name" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
          <input name="last_name" id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
          <input name="email" id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
          <textarea name="message" id="icon_prefix2" class="materialize-textarea" length="400"></textarea>
          <label for="icon_prefix2">Message</label>
        </div>
      </div>
      <div class="row">
      <div class="col s6 offset-s6 offset-m6"></div>
        <button class="btn-large waves-effect waves-light deep-orange" id="submit">Send</button>
        </div>
      </div>
    </form>
  </div>

      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="#!">Community</a></li>
            <li><a class="white-text" href="#!">Board</a></li>
            <li><a class="white-text" href="#!">Contact us</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>

landingsite/templates/landingsite/privacy-policy.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate -Privacy Policy</title>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - EPrivacy Policy" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/seoulmateapp" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." /> 
    <meta property="og:image"content="{% static 'landingsite/images/end_user_license.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/privacy-policy" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Seoul Mate</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#about-us">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
         <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#about-us">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br><br><br><br><br>
      <h2 class="header center white-text">Privacy Policy</h2>
      <div class="row center">
        <h5 class="header col s12 text-dark-orange light"><span class="text-dark-orange"></span></h5>
      </div>
      <div class="row center">
        <a href="#privacy" id="download-button" class="btn-large waves-effect waves-light deep-orange">Check below</a>
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/end_user_license.jpg' %}"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row" id="privacy">
        <h5 style="font-size: 18px;">Our Commitment To Privacy</h5>
        <p>
Your privacy is important to us. To better protect your privacy we provide this notice explaining our online information practices and the choices you can make about the way your information is collected and used. To make this notice easy to find, we make it available on our homepage and at every point where personally identifiable information may be requested.
<br><br>
<b>The Information We Collect:</b>
<br>This notice applies to all information collected or submitted on the Seoul Mate apps(android and iOS).<br>
1. Name <br>
2. Email address <br>
3. Facebook Profile Photo <br> 
4. Locale Information <br>
5. User friends on Facebook<br>
In addition we also collect analytics of the app through Google Analytics framework for iOS and Android.<br><br>
<b>The Way We Use Information:</b>
<br>
We use the information you provide about yourself in app only when you post or like/comment on a post. We do not share this information with outside parties.
<br><br>
<b>How You Can Access Or Correct Your Information</b>
 <br>
We use Facebook login for accessing your personal information, which you have declared public. You can always change your name, profile photo, or locale in your Facebook profile and it will be updated on our servers. You can also revoke access by removing Seoul Mate app from your app settings on Facebook. 
<br><br>
<b>How To Contact Us</b>
<br>
Should you have other questions or concerns about these privacy policies, please send us an email at seoulmate.me@gmail.com.
<br><br>
Updated on August 4, 2015

</p>
        <div class="col s12 m8">
        </div>

      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text" id="about-us">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
      <li><a class="white-text"  href="/blog/">Blog</a></li>
        <li><a class="white-text"  href="/collections/">Collections</a></li>
        <li><a class="white-text"  href="/daehakgyo/">Universities</a></li>
            <li><a class="white-text" href="contact-us/">Contact us</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>