blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^post$', views.boardpost, name='boardpost'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name = 'postSlug'),
    url(r'^(?P<post_id>[0-9]+)$', views.postView, name='postView'),
]

daehakgyo/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # url(r'^board/(?P<object_id>[a-zA-Z0-9]+)/$', views.postView, name='postView'),
    url(r'^$', views.index, name='index'),
     url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name='postSlug'),
    # url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name = 'postSlug'),
]

seoulmateapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^collections/', include('collection.urls', namespace="collection")),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^daehakgyo/', include('daehakgyo.urls', namespace="daehakgyo")),
    url(r'^lifeinkorea/', include('koreanlife.urls', namespace="koreanlife")),
	url(r'^end-user-license-agreement/',TemplateView.as_view(template_name='landingsite/end-user-license-agreement.html'),name='end-user-license-agreement'),
    url(r'^privacy-policy/',TemplateView.as_view(template_name='landingsite/privacy-policy.html'),name='privacy-policy'),
    url(r'^contact/thanks/',TemplateView.as_view(template_name='landingsite/thanks.html'),name='thanks'),
    url(r'^contact-us/',TemplateView.as_view(template_name='landingsite/contact_us.html'),name='contact-us'),
    url(r'^help-center/',TemplateView.as_view(template_name='landingsite/help-center.html'),name='help-center'),
    url(r'^$', include('landingsite.urls', namespace="landingsite")),
]

#urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daehakgyo/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


class University(models.Model):
	name_eng = models.CharField(max_length=450)
	name_kor = models.CharField(max_length=450)
	address_eng = models.CharField(max_length=600)
	address_kor = models.CharField(max_length=600)
	rank = models.IntegerField(default=0)
	uni_photo_small = models.ImageField(upload_to='posts/uni')
	uni_photo_banner = models.ImageField(upload_to='posts/uni')
	intro = models.TextField()
	link = models.CharField(max_length=450)
	uni_slug = models.SlugField(max_length=600,unique=True)
	updatedAt =  models.DateTimeField(auto_now=True)
	createdAt =  models.DateTimeField(auto_now_add=True)
	admission_open = models.BooleanField(default=True)
	uni_map = models.TextField(default="")
	airport_route = models.TextField(default="")

	class Meta:
		verbose_name_plural = "Universities"

	def __str__(self):
		return self.name_eng + " | " + self.name_kor

	def save(self):
		if not self.id:
			self.uni_slug = slugify(self.name_eng)
		# self.updatedAt = datetime.datetime.now()
		return super(University,self).save()

	# @classmethod
	# def create(cls,title,content,l,pos,cat,t,p,u,objectId):
	# 	uni = cls(title=title,content=content,link=l,position=pos,category=cat,thumb=t,photo=p,user=u,objectId=objectId)
	# 	return board

daehakgyo/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,Http404
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt
import json
from django.db.models import Q
from .models import University 


def index(request):
	if request.method == "GET":
		q = request.GET.get('search')
		if q:
			results = University.objects.filter(Q(name_eng__icontains=q) | Q(intro__icontains=q) | Q(name_kor__icontains=q)).order_by('createdAt')
			context = {'unis': results}
			return render(request,'daehakgyo/university_home.html', context)
		else: 
			unis = University.objects.order_by('rank')
			context = {'unis': unis}
			return render(request,'daehakgyo/university_home.html', context)


def postSlug(request,slug):
	uni = get_object_or_404(University,uni_slug=slug)
	return render(request,'daehakgyo/university_single.html', {'uni':uni})

# def search(request):
# 	context = ""
# 	if request.method == "GET":
# 		q = request.GET['search']
# 		results = University.objects.filter(Q(name_eng__icontains=q) | Q(intro__icontains=q) | Q(name_kor__icontains=q)).order_by('createdAt')
# 		context = {'unis': results}
# 	return render(request,'daehakgyo/university_home.html', context)

daehakgyo/templates/daehakgyo/university_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - Universities</title>
  <link rel="icon" type="image/png" href="{% static 'landingsite/images/favicon.ico' %}">

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:title" content="Seoul Mate - Universities" />
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/seoulmateapp" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." />
    <meta property="og:image"content="{% static 'landingsite/images/university_share_fb.jpg' %}"
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/daehakgyo/" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Universities</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections/">Collections</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="container">
  <nav class="teal">
    <div class="nav-wrapper">
      <form action="{% url 'daehakgyo:index' %}" method="get">
        <div class="input-field">
          <input id="search" type="search" name="search" required>
          <label for="search"><i class="material-icons">search</i></label>
          <i class="material-icons">close</i>
        </div>
        <!-- <input type="submit" value="Search" /> -->
      </form>
    </div>
  </nav>
</div>
  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
      {% if unis %}
      {% for uni in unis %}
        <div class="col s12 m4 l4" style="height:415px;">
          <div class="card">
            <div class="card-image">
            {% if uni.uni_photo_small %}
              <img height="183" src="{{ uni.uni_photo_small.url }}">
            {% endif %}
            </div>
            <div class="card-content">
            <span class="card-title activator grey-text text-darken-4 truncate" style="font-size: 17px;">{{ uni.name_eng}} {{ uni.name_kor}} </span>
            <p><a  class="deep-purple-text text-accent-2" href="/daehakgyo/{{ uni.uni_slug }}">Read more</a></p>
            </div>
            <div class="card-action">
              <a style="color: #ff4081;" href="#"><span class="teal-text text-accent-3"> {{ uni.address_eng }}
              </span></a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h3>No University entered yet</h3>
        {% endif %}
      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="/collections/">Collections</a></li>
            <li><a class="white-text" href="#!">Features</a></li>
            <li><a class="white-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4"
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>

daehakgyo/templates/daehakgyo/university_single.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>{{ uni.name_eng }}</title>
  <link rel="icon" type="image/png" href="{% static 'landingsite/images/favicon.ico' %}">
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta property="og:title" content="{{ uni.name_eng }}" />
  <meta property="og:description" content="{{ uni.intro }}" />
  <meta property="og:image"content="http://seoulmateapp.co{{ uni.uni_photo_banner.url }}" 
    />
   <meta property="fb:app_id" content="222622874583781" />
  <meta property="og:url" content="http://seoulmateapp.co/daehakgyo/{{ uni.uni_slug }}" />

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

  </script>
</head>
<body>
<div id="fb-root"></div>
{% block js %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '222622874583781',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
{% endblock js %}
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/daehakgyo/" class="brand-logo">Universities</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/"><i class="material-icons">home</i></a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <!-- <div class="parallax-container" id="index-banner"> -->
      {% if uni.uni_photo_banner %} 
      <div class="section teal" style="background-image: url({{ uni.uni_photo_banner.url }});">
              {% else %}
      <div class="section teal">
        {% endif %}
        <div class="row center" >
          <div class="col s12 m8 l8 offset-m2 offset-l2">
           <br><br>
          <h3 class="grey-text text-darken-4">{{ uni.name_eng }} {{ uni.name_kor }}</h3>
          <br><br> <br><br><br><br>
          <!-- <p class="grey-text text-darken-3">{{ uni.intro }}</p> -->
          </div>
        </div>
      </div>
      <div class="container">
      <div class="row">
      <br><br>
        <div class="col s12 m4 l4">
           <ul class="collection with-header">
        <li class="collection-header"><h4>Information</h4></li>
        <li class="collection-item"><div>Rank : {{ uni.rank }}<a href="http://www.usnews.com/education/best-global-universities/south-korea" target="_blank" class="secondary-content deep-purple-text text-accent-2"><i class="material-icons">star</i></a></div></li>
        {% if uni.admission_open %}
        <li class="collection-item"><div>Admission Open<a href="#!" class="secondary-content deep-purple-text text-accent-2"><i class="material-icons">event_available</i></a></div></li>
        {% else %}
         <li class="collection-item"><div>Admission Closed<a href="#!" class="secondary-content deep-purple-text text-accent-2"><i class="material-icons">event_busy</i></a></div></li>
        {% endif %}
   <!--      <li class="collection-item"><div>Alvin<a href="#!" class="secondary-content"><i class="material-icons">send</i></a></div></li> -->
        <li class="collection-item"><div>University link<a href="{{ uni.link }}" class="secondary-content deep-purple-text text-accent-2"><i class="material-icons">link</i></a></div></li>
      </ul>
        </div>
         <div class="col s12 m8 l8">
         <h5>Introduction:</h5>
          <h6 style="line-height: 140%;">{{ uni.intro }}</h6>
          <h5>How to get there:</h5>
          <p>{{ uni.airport_route|safe}}</p>
         </div>
      </div>
      <div class="divider"></div>
      <div class="section">
          <div class="row">
          <div class="col s12 m12 l12">
          <div class="video-container">
            {{ uni.uni_map|safe }}
          </div>
          </div>
        </div>
      </div>
    </div>
  <!-- </div> -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large deep-purple accent-2">
      <i class="large material-icons">share</i>
    </a>
    <ul>
      <li><a class="btn-floating blue darken-1" 
      href="https://www.linkedin.com/shareArticle?mini=true&url=http://seoulmateapp.co/daehakgyo/{{uni.uni_slug}}&title={{ post.title|urlencode }}&summary={{ post.content|urlencode }}&source=Seoul%20Mate"
      ><i class="fa  fa-linkedin  fa-2x" style="color:#fff;"></i></a></li>
      <li><a class="btn-floating light-blue darken-4" href="" onclick="fbshare()"><i class="fa  fa-facebook  fa-2x"></i></a></li>
      <li><a class="btn-floating light-blue accent-3" href="https://twitter.com/intent/tweet?text={{uni.name_eng|urlencode}}&url={{ 'http://seoulmateapp.co/daehakgyo/'|urlencode:''}}{{ uni.uni_slug|urlencode:''}}&via=seoulmate_me"><i class="fa  fa-twitter  fa-2x"></i></a></li>
      <li><a class="btn-floating red darken-2" href="https://plus.google.com/share?url={{ 'http://seoulmateapp.co/daehakgyo/'|urlencode:''}}{{ uni.uni_slug|urlencode:''}}"><i class="fa fa-google-plus fa-2x"></i></a></li>
    </ul>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/latest">Blog</a></li>
            <li><a class="white-text" href="#!">MOOC Circle</a></li>
            <li><a class="white-text" href="#!">Seoul Mate</a></li>
            <li><a class="white-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmateme">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" 
      href="http://materializecss.com">Materialize</a> and
       <a class="teal-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>

<script>
    function fbshare(){
        FB.ui({
          method: 'share',
          href: 'http://seoulmateapp.co/daehakgyo/{{ uni.uni_slug }}',
          picture: 'http://seoulmateapp.co{{ uni.uni_photo_banner.url }}',
          caption: '{{ uni.name_eng }}',
        }, function(response){});
    }
</script>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>