blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	url(r'^post$', views.boardpost, name='boardpost'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.postSlug, name = 'postSlug'),
    url(r'^(?P<post_id>[0-9]+)$', views.postView, name='postView'),
]

resources/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^(?P<slug>[-_\w]+)/$', views.resource_cat, name = 'resource_cat'),
    url(r'^$', views.index, name='index'),
]

seoulmateapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^collections/', include('collection.urls', namespace="collection")),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^daehakgyo/', include('daehakgyo.urls', namespace="daehakgyo")),
    url(r'^lifeinkorea/', include('koreanlife.urls', namespace="koreanlife")),
	url(r'^end-user-license-agreement/',TemplateView.as_view(template_name='landingsite/end-user-license-agreement.html'),name='end-user-license-agreement'),
    url(r'^privacy-policy/',TemplateView.as_view(template_name='landingsite/privacy-policy.html'),name='privacy-policy'),
    url(r'^contact/thanks/',TemplateView.as_view(template_name='landingsite/thanks.html'),name='thanks'),
    url(r'^contact-us/',TemplateView.as_view(template_name='landingsite/contact_us.html'),name='contact-us'),
    url(r'^help-center/',TemplateView.as_view(template_name='landingsite/help-center.html'),name='help-center'),
    url(r'^$', include('landingsite.urls', namespace="landingsite")),
]

#urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resources/templates/resources/resource_cat_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - {{ cat.title }}</title>
  <link rel="icon" type="image/png" href="{% static 'landingsite/images/favicon.ico' %}">

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - {{ cat.title }}" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/seoulmateapp" />
    <meta property="og:description" content="The Korean Alphabet Day, known as Hangeul Day in South Korea, and Chosŏn'gŭl Day in North Korea, is a national Korean commemorative day marking the invention and the proclamation of Hangul (한글; 조선글), the alphabet of the Korean language, by the 15th-century Korean monarch Sejong the Great.." /> 
    <meta property="og:image"content="{% static 'landingsite/images/hangeul_day_pic.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/resources/{{ cat.slug }}" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Korean Resources</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="#">About</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br><br><br><br><br>
      <h1 class="header center black-text">{{ cat.title }}</h1>
      <div class="row center">
      </div>
      <div class="row center">
        <a href="#resources" id="download-button" class="btn-large waves-effect waves-light deep-orange">Check below</a>
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/hangeul_day_pic.jpg' %}"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
      {% if posts %}
      {% for post in posts %}
        <div class="col s12 m4" id="resources" >
          <div class="card" style="height:280px;">
            <div class="card-content grey-text">
            <span class="card-title teal-text" style="font-size: 21px;">{{ post.site_title|truncatechars:80 }} <a href="{{ post.site_url }}"><i class="small material-icons">link</i></a></span>
            <p>{{ post.description|truncatechars:100 }}</p>
            </div>
            <div class="card-action">
            <a class="pink-text accent-2" href="#">{{ post.tags }}</a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h3>No posts are available.</h3>
        {% endif %}
      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="/collections/">Collections</a></li>
            <li><a class="white-text" href="#!">Features</a></li>
            <li><a class="black-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmate_me">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>

resources/templates/resources/resources_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Seoul Mate - Resources</title>
  <link rel="icon" type="image/png" href="{% static 'landingsite/images/favicon.ico' %}">

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="{% static 'landingsite/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!-- Fb Tags-->
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" /> 
    <meta property="og:title" content="Seoul Mate - Resources" /> 
    <meta property="og:site_name" content="Seoul Mate"/>
    <meta property="article:author" content="https://www.facebook.com/seoulmateapp" />
    <meta property="og:description" content="Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university." /> 
    <meta property="og:image"content="{% static 'landingsite/images/hangeul_day_pic.jpg' %}" 
    />
    <meta property="fb:app_id" content="222622874583781" />
    <meta property="og:url" content="http://seoulmateapp.co/resources/" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49202305-2', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <nav class="teal darken-2" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Resources</a>
      <ul class="right hide-on-med-and-down">
        <li class="white-text"><a href="#" class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Coming soon"  id="navacolor">Features</a></li>
        <li><a href="/blog/" id="navacolor">Blog</a></li>
        <li><a href="/collections" id="navacolor">Collections</a></li>
        <li><a href="/daehakgyo/" id="navacolor">Universities</a></li>
        <li><a href="/lifeinkorea/" id="navacolor">Life in Korea</a></li>
        <li><a href="/resources/" id="navacolor">Resources</a></li>
        <li><a href="/contact-us/" id="navacolor">Contact us</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a class="tooltipped" data-position="right" data-delay="50" data-tooltip="Coming soon" href="#">Features</a></li>
        <li><a href="/blog/">Blog</a></li>
        <li><a href="/collections">Collections</a></li>
        <li><a href="/daehakgyo/">Universities</a></li>
        <li><a href="/lifeinkorea/" >Life in Korea</a></li>
        <li><a href="/resources/" >Resources</a></li>
        <li><a href="/contact-us/">Contact us</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
  <div class="parallax-container" id="index-banner">
    <div class="container">
      <br><br><br><br><br><br>
      <h1 class="header center black-text">Seoul Mate Resources</h1>
      <div class="row center">
        <h5 class="header col s12 blac-text"><span class="text-dark-orange"></span>Posts grouped by Category</h5>
      </div>
      <div class="row center">
        <a href="#" id="download-button" class="btn-large waves-effect waves-light deep-orange">Check below</a>
      </div>
      <br><br>

    </div>
     <div class="parallax"><img src="{% static 'landingsite/images/hangeul_day_pic.jpg' %}"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
      {% if cats %}
      {% for cat in cats %}
        <div class="col s12 m4">
          <div class="card" style="height:415px;">
          {% if cat.photo %}
            <div class="card-image" >
              <img height="200" src="{{ cat.photo.url }}">
            </div>
          {% endif %}
            <div class="card-content">
            <span class="card-title activator grey-text text-darken-4 truncate" style="font-size: 21px;">{{ cat.title}}</span>
            <p><a  class="deep-orange-text" href="{% url 'resources:resource_cat' cat.slug %}">Read more</a></p>
            </div>
            <div class="card-action">
              <a style="color: #ff4081;" href="#"><span class="teal-text text-accent-3"> 
              </span></a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h3>No posts are available.</h3>
        {% endif %}
      </div>
    </div>
    <br><br>
    <div class="section">
    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
           <h5 class="white-text">About us</h5>
          <p class="grey-text text-lighten-4">Seoul Mate is an information and resource sharing app for International Students in South Korea.Seoul Mate lets you post your question, find friends from your university, and get updates about jobs, internships, scholarships and more. Seoul Mate is the perfect way to keep up with your friends in South Korea. It also provides you with campus maps so that you don't get lost on first day at your university.</p>
        </div>
        <div class="col l3 s12">
         <h5 class="white-text">Important Links</h5>
          <ul>
            <li><a class="white-text" href="/blog/">Blog</a></li>
            <li><a class="white-text" href="/collections/">Collections</a></li>
            <li><a class="white-text" href="#!">Features</a></li>
            <li><a class="black-text" href="end-user-license-agreement/">End User License Agreement</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://twitter.com/seoulmate_me">Twitter</a></li>
            <li><a class="white-text" href="https://github.com/seoulmate">Github</a></li>
            <li><a class="white-text" href="https://medium.com/seoul-mate-blog">Medium</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/company/3662789">Linkedin</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      and <a class="yellow-text text-darken-4" 
       href="http://djangoproject.com">Django</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <script src="{% static 'landingsite/js/init.js' %}"></script>

  </body>
</html>